from ugnn.architectures.mlp import MLP
from ugnn.architectures.gcn import GCN
from ugnn.architectures.appnp import APPNP
from ugnn.architectures.gat import GAT
from ugnn.architectures.jacobi import JacobiConv
from ugnn.architectures.fdiff import FDiff
from ugnn.architectures.deepset import DeepSet
from ugnn.architectures.s2gc import S2GC
from ugnn.architectures.gcnii import GCNII
from ugnn.architectures.universalp import UniversalP
from ugnn.architectures.universal import Universal
